export const manifests =[
    {
        name: 'Update Seal No. Details',
        id: 'update-sealNo-tab',
        control: 'update-sealNo',
        status: 0,
        key: 'update-sealNo',
    },
    {
        name: 'Update Container Cell Position',
        id: 'update-container-cell-tab',
        control: 'update-container-cell',
        status: 0,
        key: 'update-container-cell',
    },
    {
        name: 'IGM Generation',
        id: 'igm-generation-tab',
        control: 'igm-generation',
        status: 0,
        key: 'igm-generation',
    },
    {
        name: 'Update Master BL',
        id: 'update-master-bl-tab',
        control: 'update-master-bl',
        status: 0,
        key: 'update-master-bl',
    },
    // {
    //     name: 'Update BL Status ',
    //     id: 'update-bl-status-tab',
    //     control: 'update-bl-status',
    //     status: 0,
    //     key: 'update-bl-status',
    // },
    {
        name: 'Update CFS',
        id: 'update-cfs-tab',
        control: 'update-cfs',
        status: 0,
        key: 'update-cfs',
    },
    {
        name: 'Update Item No',
        id: 'update-item-no-tab',
        control: 'update-item-no',
        status: 0,
        key: 'update-item-no',
    },
    {
        name: 'Update TP No & TP Date',
        id: 'update-tp',
        control: 'update-tp',
        status: 0,
        key: 'update-tp',
    },
    {
        name: 'Update Freight',
        id: 'update-freight-tab',
        control: 'update-freight',
        status: 0,
        key: 'update-freight',
    },
    {
        name: 'Update IGM No and Date',
        id: 'update-igm-no-date-tab',
        control: 'update-igm-no-date',
        status: 0,
        key: 'update-igm-no-date',
    },
    {
        name: 'Update BL Checklist',
        id: 'update-checklist-tab',
        control: 'update-checklist',
        status: 0,
        key: 'update-checklist',
    },
    {
        name: 'Update Cargo Type/Departure Mode',
        id: 'update-cargo-departure-tab',
        control: 'update-cargo-departure',
        status: 0,
        key: 'update-cargo-departure',
    },
    {
        name: 'Update Load Port Remarks',
        id: 'update-loadport-remarks-tab',
        control: 'update-loadport-remarks',
        status: 0,
        key: 'update-loadport-remarks',
    },
    {
        name: 'Update Slot Bl',
        id: 'update-slot-bl-tab',
        control: 'update-slot-bl',
        status: 0,
        key: 'update-slot-bl',
    },
    {
        name: 'Edit Terminal/FPOD',
        id: 'edit-terminal-fpod-tab',
        control: 'edit-terminal-fpod',
        status: 0,
        key: 'edit-terminal-fpod',
    },
    {
        name: 'Edit Terminal/FPOD Container Wise',
        id: 'edit-terminal-fpod-container-tab',
        control: 'edit-terminal-fpod-container',
        status: 0,
        key: 'edit-terminal-fpod-container',
    },
    {
        name: 'Update IGM Details',
        id: 'update-igm-tab',
        control: 'update-igm',
        status: 0,
        key: 'update-igm',
    },
    {
        name: 'Update BOND',
        id: 'update-bond-tab',
        control: 'update-bond',
        status: 0,
        key: 'update-bond',
    },
    // {
    //     name: ' Update REEFER',
    //     id: 'update-reefer-tab',
    //     control: 'update-reefer',
    //     status: 0,
    //     key: 'update-reefer',
    // },
    // {
    //     name: 'Update Sub Line & Item No',
    //     id: 'update-subline-tab',
    //     control: 'update-subline',
    //     status: 0,
    //     key: 'update-subline',
    // },
    {
        name: ' View Master BL(s)',
        id: 'view-master-bl-tab',
        control: 'view-master-bl',
        status: 0,
        key: 'view-master-bl',
    },
    // {
    //     name: 'Update Sub Line[1]  & Item No[2]  For SCMT',
    //     id: 'update-subline-SCMT-tab',
    //     control: 'update-subline-SCMT',
    //     status: 0,
    //     key: 'update-subline-SCMT',
    // },
    {
        name: ' View SOC Containers',
        id: 'view-SOC-tab',
        control: 'view-SOC',
        status: 0,
        key: 'view-SOC',
    },
    
    // {
    //     name: 'Bapli Upload',
    //     id: 'bapli-upload-tab',
    //     control: 'bapli-upload',
    //     status: 0,
    //     key: 'bapli-upload',
    // },
    {
        name: 'Update Product Details',
        id: 'update-product-tab',
        control: 'update-product',
        status: 0,
        key: 'update-product',
    },
    // {
    //     name: 'Update Container Weight (From BL)',
    //     id: 'update-container-weight-tab',
    //     control: 'update-container-weight',
    //     status: 0,
    //     key: 'update-container-weight',
    // },
 
    // {
    //     name: 'Update Load Port Remark',
    //     id: 'update-loadport-remark-tab',
    //     control: 'update-loadport-remark',
    //     status: 0,
    //     key: 'update-loadport-remark',
    // },
    
    // {
    //     name: 'Manifest Approved Wise BI Print',
    //     id: 'bi-print-tab',
    //     control: 'bi-print',
    //     status: 0,
    //     key: 'bi-print',
    // },
    {
        name: 'View CFS Wise Summary',
        id: 'cfs-summary-tab',
        control: 'cfs-summary',
        status: 0,
        key: 'cfs-summary',
    },
    {
        name: 'IGM Checklist – Consignee',
        id: 'checklist-igm-tab',
        control: 'checklist-igm',
        status: 0,
        key: 'checklist-igm',
    },
    {
        name: 'Update IGM Number And Date',
        id: 'update-igmno-tab',
        control: 'update-igmno',
        status: 0,
        key: 'update-igmno',
    },
   
    // {
    //     name: 'Update Packages',
    //     id: 'update-packages-tab',
    //     control: 'update-packages',
    //     status: 0,
    //     key: 'update-packages',
    // },
    // {
    //     name: 'CMC Permission',
    //     id: 'cmc-permission-tab',
    //     control: 'cmc-permission',
    //     status: 0,
    //     key: 'cmc-permission',
    // },
    // {
    //     name: 'Auto Load Charges',
    //     id: 'auto-load-charges-tab',
    //     control: 'auto-load-charges',
    //     status: 0,
    //     key: 'auto-load-charges',
    // },



]
   