export const shared = {
    items: [
        {
            "source": {
                "locationId": 1114,
                "city": "Mundra",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUN"
            },
            "destination": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "customerName": "Australia1",
            "quoteId": 6575,
            "quoteName": "Q240406575",
            "quoteDate": "2024-04-22T00:00:00",
            "quoteType": 96,
            "carbonKWG": "0",
            "carbonEmission": "0",
            "cargoReadyDate": "2024-04-29T18:30:00+00:00",
            "quoteTerms": "2024-04-25T00:00:00",
            "quoteService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":false,\"road\":{\"origin\":false,\"destination\":false},\"rail\":{\"origin\":false,\"destination\":false}},\"custom\":{\"origin\":false,\"destination\":false},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":false,\"at_factory\":false},\"destuffling\":{\"at_cfs\":false,\"at_factory\":false}}}",
            "cargoHaz": false,
            "tradeFinance": true,
            "carbonFootprint": true,
            "containerDetails": "[{\"container_id\":0,\"container_type\":\"\",\"quantity\":0}]",
            "orgId": 434,
            "quoteSensitivity": "Cost sensitive",
            "quotePaymentTerms": null,
            "quoteRate": "{\"estimate\":\"\"}",
            "cargoType": "General",
            "salesPerson": null,
            "assignedTo": null,
            "quoteAmount": 0,
            "quoteAccepted": null,
            "quoteUser": null,
            "quoteStatus": "quote-requested",
            "quoteTags": null,
            "quoteItemOption": null,
            "bookingId": null,
            "bookingNumber": null,
            "internalStatus": "quote-enquiry",
            "additionalService": "{\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":null,\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "loadType": "Ocean LCL",
            "createdAt": "2024-04-22T00:00:00",
            "updatedAt": "2024-04-22T00:00:00",
            "createdBy": 444,
            "updatedBy": 444,
            "quoteRemarks": "",
            "toLocation": 1241,
            "fromLocation": 1114,
            "por": null,
            "pdaAccount": null,
            "cancelRemarks": null,
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": "{}",
            "palletDetails": "[{\"palletType\":\"1219 mm x 1016 mm\",\"palletHeight\":12000,\"quantity\":10,\"volume\":148.62,\"volumeParameter\":\"cubic meter\"}]"
        },
        {
            "source": {
                "locationId": 1114,
                "city": "Mundra",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUN"
            },
            "destination": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "customerName": "Australia1",
            "quoteId": 6574,
            "quoteName": "Q240406574",
            "quoteDate": "2024-04-22T00:00:00",
            "quoteType": 96,
            "carbonKWG": "0",
            "carbonEmission": "0",
            "cargoReadyDate": "2024-04-29T18:30:00+00:00",
            "quoteTerms": "2024-04-25T00:00:00",
            "quoteService": "",
            "cargoHaz": false,
            "tradeFinance": true,
            "carbonFootprint": true,
            "containerDetails": "[{\"container_id\":61521,\"container_type\":\"40 Standard Dry\",\"quantity\":5}]",
            "orgId": 434,
            "quoteSensitivity": "Cost sensitive",
            "quotePaymentTerms": null,
            "quoteRate": "",
            "cargoType": "General",
            "salesPerson": null,
            "assignedTo": null,
            "quoteAmount": 12699.75,
            "quoteAccepted": "2024-04-22T10:19:58.222",
            "quoteUser": "",
            "quoteStatus": "quote-booked",
            "quoteTags": null,
            "quoteItemOption": "preffered",
            "bookingId": 949,
            "bookingNumber": null,
            "internalStatus": "quote-booked",
            "additionalService": "{\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":null,\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "loadType": "Ocean FCL",
            "createdAt": "2024-04-22T00:00:00",
            "updatedAt": "2024-04-22T00:00:00",
            "createdBy": 444,
            "updatedBy": 444,
            "quoteRemarks": "",
            "toLocation": 1241,
            "fromLocation": 1114,
            "por": null,
            "pdaAccount": null,
            "cancelRemarks": null,
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": "{}",
            "palletDetails": "[{\"palletType\":\"\",\"quantity\":\"\"}]"
        },
        {
            "source": {
                "locationId": 1114,
                "city": "Mundra",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUN"
            },
            "destination": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "customerName": "Australia1",
            "quoteId": 6573,
            "quoteName": "Q240406573",
            "quoteDate": "2024-04-22T00:00:00",
            "quoteType": 96,
            "carbonKWG": "0",
            "carbonEmission": "0",
            "cargoReadyDate": "2024-04-29T18:30:00+00:00",
            "quoteTerms": "2024-04-22T00:00:00",
            "quoteService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":false,\"road\":{\"origin\":false,\"destination\":false},\"rail\":{\"origin\":false,\"destination\":false}},\"custom\":{\"origin\":false,\"destination\":false},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":false,\"at_factory\":false},\"destuffling\":{\"at_cfs\":false,\"at_factory\":false}}}",
            "cargoHaz": false,
            "tradeFinance": true,
            "carbonFootprint": true,
            "containerDetails": "[{\"container_id\":61521,\"container_type\":\"40 Standard Dry\",\"quantity\":5}]",
            "orgId": 434,
            "quoteSensitivity": "Cost sensitive",
            "quotePaymentTerms": null,
            "quoteRate": "{\"estimate\":\"\"}",
            "cargoType": "General",
            "salesPerson": null,
            "assignedTo": null,
            "quoteAmount": 0,
            "quoteAccepted": null,
            "quoteUser": null,
            "quoteStatus": "quote-draft",
            "quoteTags": null,
            "quoteItemOption": null,
            "bookingId": null,
            "bookingNumber": null,
            "internalStatus": null,
            "additionalService": "{\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":null,\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "loadType": "Ocean FCL",
            "createdAt": "2024-04-22T00:00:00",
            "updatedAt": "2024-04-22T00:00:00",
            "createdBy": 444,
            "updatedBy": 444,
            "quoteRemarks": "",
            "toLocation": 1241,
            "fromLocation": 1114,
            "por": null,
            "pdaAccount": null,
            "cancelRemarks": null,
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": "{}",
            "palletDetails": "[{\"palletType\":\"\",\"quantity\":\"\"}]"
        },
        {
            "source": {
                "locationId": 1114,
                "city": "Mundra",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUN"
            },
            "destination": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "customerName": "Australia1",
            "quoteId": 6568,
            "quoteName": "Q240406568",
            "quoteDate": "2024-04-19T00:00:00",
            "quoteType": 96,
            "carbonKWG": "0",
            "carbonEmission": "0",
            "cargoReadyDate": "2024-04-24T00:00:00+00:00",
            "quoteTerms": "2024-04-22T00:00:00",
            "quoteService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":true,\"road\":{\"origin\":true,\"destination\":false},\"rail\":{\"origin\":true,\"destination\":false}},\"custom\":{\"origin\":true,\"destination\":true},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":false,\"at_factory\":true},\"destuffling\":{\"at_cfs\":false,\"at_factory\":false}}}",
            "cargoHaz": false,
            "tradeFinance": true,
            "carbonFootprint": true,
            "containerDetails": "[{\"container_id\":61522,\"container_type\":\"20 Standard Dry\",\"quantity\":2}]",
            "orgId": 434,
            "quoteSensitivity": "Cost sensitive",
            "quotePaymentTerms": null,
            "quoteRate": "{\"estimate\":{}}",
            "cargoType": "General",
            "salesPerson": null,
            "assignedTo": null,
            "quoteAmount": 0,
            "quoteAccepted": null,
            "quoteUser": null,
            "quoteStatus": "quote-requested",
            "quoteTags": null,
            "quoteItemOption": null,
            "bookingId": null,
            "bookingNumber": null,
            "internalStatus": "quote-enquiry",
            "additionalService": "{\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":{},\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "loadType": "Ocean FCL",
            "createdAt": "2024-04-19T00:00:00",
            "updatedAt": "2024-04-19T00:00:00",
            "createdBy": 444,
            "updatedBy": 444,
            "quoteRemarks": "Handle with care",
            "toLocation": 1241,
            "fromLocation": 1114,
            "por": null,
            "pdaAccount": null,
            "cancelRemarks": null,
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": "{}",
            "palletDetails": "[{\"palletType\":\"\",\"quantity\":\"\"}]"
        }
    ],

    items1: [
        {
            "source": {
                "locationId": 1114,
                "city": "Mundra",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUN"
            },
            "destination": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "insurance": false,
            "containers": [],
            "bookingIssue": 0,
            "customerName": "Australia1",
            "dateNote": null,
            "loyatyPoints": 0,
            "bookingPercent": 0,
            "bookingId": 949,
            "bookingName": "B240400949",
            "bookingDate": "2024-04-22T00:00:00",
            "bookingType": null,
            "fromLocation": 1114,
            "toLocation": 1241,
            "pickAddress": 0,
            "dropAddress": 0,
            "cargoHazRemarks": null,
            "cargoRefer": "",
            "carbonKWG": "0",
            "carbonEmission": "0",
            "quoteRemarks": "",
            "bookingService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":false,\"road\":{\"origin\":false,\"destination\":false},\"rail\":{\"origin\":false,\"destination\":false}},\"custom\":{\"origin\":false,\"destination\":false},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":false,\"at_factory\":false},\"destuffling\":{\"at_cfs\":false,\"at_factory\":false}},\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":null,\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "cargoReadyDate": "2024-04-29T18:30:00+00:00",
            "bookingTerms": null,
            "tripId": "",
            "vesselId": null,
            "voyoageId": null,
            "cargoHaz": false,
            "incoterm": "CIF",
            "carbonFootprint": true,
            "tradeFinance": true,
            "bookingAmount": 12699.75,
            "bookingStatus": "booking-requested",
            "bookingTags": "{}",
            "bookingAssignedTo": null,
            "salesPerson": null,
            "bookingUser": null,
            "additionalService": "{\"isaddition_service\":false,\"addition_service\":null,\"cargo_insurance\":null,\"iscarbon_offset\":false,\"carbon_offset\":null,\"special_request\":\"\"}",
            "bookingCurrency": null,
            "bookingETA": null,
            "bookingNumber": null,
            "bookingPrice": 0,
            "orgId": 434,
            "quoteId": 6574,
            "createdAt": "2024-04-22T00:00:00",
            "updatedAt": "2024-04-23T00:00:00",
            "createdBy": 444,
            "updatedBy": 444,
            "shipmentDate": "2024-04-22T00:00:00",
            "vesselImo": 0,
            "quoteNumber": null,
            "container": "[{\"container_id\":61521,\"container_type\":\"40 Standard Dry\",\"quantity\":5}]",
            "internalStatus": "booking-linebooking",
            "loadType": "Ocean FCL",
            "taxInfo": "{\"id\":321,\"title\":\"PREFERRED PARTNER\",\"isShow\":true,\"price\":12699.75,\"transit_time\":\"15\",\"Carrier\":\"American President Lines (APL)\",\"icd\":null,\"pol\":{\"locationId\":1114,\"locationName\":\"Mundra\",\"isActive\":true,\"locationCode\":\"INMUN\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"pod\":{\"locationId\":1241,\"locationName\":\"Jebel Ali\",\"isActive\":true,\"locationCode\":\"AEJEA\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"cutoffdate\":\"2024-04-22T10:13:46.066Z\",\"sailingdate\":\"2024-04-22T10:13:44.824Z\",\"handoverDate\":\"2024-04-29T18:30:00\+00:00\",\"originDetentionDays\":null,\"originDemurrageDays\":null,\"destinationDetentionDays\":null,\"destinationDemurrageDays\":null,\"gst\":1937.25,\"payTerm\":null,\"quoteSensitivity\":\"Cost sensitive\"}",
            "isSailOnBooking": true,
            "isPayLater": false,
            "daysLater": 0,
            "vesselName": null,
            "sailingDate": null,
            "issues": [],
            "bookingETD": null,
            "containerList": [],
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "bookingPaymentTerms": null,
            "por": null,
            "pdaAccount": null,
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": "{}",
            "palletDetails": "[{\"palletType\":\"\",\"quantity\":\"\"}]"
        },
        {
            "source": {
                "locationId": 1114,
                "city": "Mundra",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUN"
            },
            "destination": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "insurance": false,
            "containers": [],
            "bookingIssue": 0,
            "customerName": "Australia1",
            "dateNote": null,
            "loyatyPoints": 0,
            "bookingPercent": 0,
            "bookingId": 947,
            "bookingName": "B240400947",
            "bookingDate": "2024-04-18T00:00:00",
            "bookingType": null,
            "fromLocation": 1114,
            "toLocation": 1241,
            "pickAddress": 0,
            "dropAddress": 0,
            "cargoHazRemarks": null,
            "cargoRefer": "",
            "carbonKWG": "0",
            "carbonEmission": "0",
            "quoteRemarks": "",
            "bookingService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":false,\"road\":{\"origin\":false,\"destination\":false},\"rail\":{\"origin\":false,\"destination\":false}},\"custom\":{\"origin\":false,\"destination\":false},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":false,\"at_factory\":false},\"destuffling\":{\"at_cfs\":false,\"at_factory\":false}},\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":null,\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "cargoReadyDate": "2024-04-23T18:30:00+00:00",
            "bookingTerms": null,
            "tripId": "",
            "vesselId": null,
            "voyoageId": null,
            "cargoHaz": false,
            "incoterm": "CIF",
            "carbonFootprint": true,
            "tradeFinance": true,
            "bookingAmount": 123751.93237778197,
            "bookingStatus": "booking-completed",
            "bookingTags": "{}",
            "bookingAssignedTo": null,
            "salesPerson": null,
            "bookingUser": null,
            "additionalService": "{\"isaddition_service\":false,\"addition_service\":[],\"cargo_insurance\":null,\"iscarbon_offset\":false,\"carbon_offset\":null,\"special_request\":\"\"}",
            "bookingCurrency": null,
            "bookingETA": null,
            "bookingNumber": null,
            "bookingPrice": 0,
            "orgId": 434,
            "quoteId": 6556,
            "createdAt": "2024-04-18T00:00:00",
            "updatedAt": "2024-04-23T00:00:00",
            "createdBy": 444,
            "updatedBy": 442,
            "shipmentDate": "2024-04-18T00:00:00",
            "vesselImo": 0,
            "quoteNumber": null,
            "container": "[{\"container_id\":0,\"container_type\":\"\",\"quantity\":0}]",
            "internalStatus": "booking-completed",
            "loadType": "Ocean LCL",
            "taxInfo": "{\"id\":321,\"title\":\"PREFERRED PARTNER\",\"isShow\":true,\"price\":123751.93237778197,\"transit_time\":\"12\",\"Carrier\":\"American President Lines (APL)\",\"icd\":null,\"pol\":{\"locationId\":1114,\"locationName\":\"Mundra\",\"isActive\":true,\"locationCode\":\"INMUN\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"pod\":{\"locationId\":1241,\"locationName\":\"Jebel Ali\",\"isActive\":true,\"locationCode\":\"AEJEA\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"cutoffdate\":\"2024-04-18T08:24:44.686Z\",\"sailingdate\":\"2024-04-18T08:24:43.998Z\",\"handoverDate\":\"2024-04-23T18:30:00\+00:00\",\"originDetentionDays\":null,\"originDemurrageDays\":null,\"destinationDetentionDays\":null,\"destinationDemurrageDays\":null,\"gst\":18877.413413559963,\"payTerm\":null,\"quoteSensitivity\":\"Cost sensitive\"}",
            "isSailOnBooking": true,
            "isPayLater": false,
            "daysLater": 0,
            "vesselName": null,
            "sailingDate": null,
            "issues": [],
            "bookingETD": null,
            "containerList": [],
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "bookingPaymentTerms": null,
            "por": null,
            "pdaAccount": null,
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": "{}",
            "palletDetails": "[{\"palletType\":\"1219 mm x 1016 mm\",\"quantity\":12}]"
        },
        {
            "source": {
                "locationId": 1114,
                "city": "Mundra",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUN"
            },
            "destination": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "insurance": false,
            "containers": [],
            "bookingIssue": 0,
            "customerName": "Australia1",
            "dateNote": null,
            "loyatyPoints": 0,
            "bookingPercent": 0,
            "bookingId": 946,
            "bookingName": "B240400946",
            "bookingDate": "2024-04-18T00:00:00",
            "bookingType": null,
            "fromLocation": 1114,
            "toLocation": 1241,
            "pickAddress": 607,
            "dropAddress": 605,
            "cargoHazRemarks": null,
            "cargoRefer": "",
            "carbonKWG": "0",
            "carbonEmission": "0",
            "quoteRemarks": "",
            "bookingService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":true,\"road\":{\"origin\":true,\"destination\":true},\"rail\":{\"origin\":true,\"destination\":false}},\"custom\":{\"origin\":true,\"destination\":false},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":false,\"at_factory\":true},\"destuffling\":{\"at_cfs\":false,\"at_factory\":true}},\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":null,\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "cargoReadyDate": "2024-04-24T18:30:00+00:00",
            "bookingTerms": null,
            "tripId": "",
            "vesselId": "sdad33",
            "voyoageId": null,
            "cargoHaz": false,
            "incoterm": "CIF",
            "carbonFootprint": true,
            "tradeFinance": true,
            "bookingAmount": 13838559.838145467,
            "bookingStatus": "booking-requested",
            "bookingTags": "{}",
            "bookingAssignedTo": null,
            "salesPerson": null,
            "bookingUser": null,
            "additionalService": "{\"isaddition_service\":false,\"addition_service\":null,\"cargo_insurance\":null,\"iscarbon_offset\":false,\"carbon_offset\":null,\"special_request\":\"\"}",
            "bookingCurrency": null,
            "bookingETA": null,
            "bookingNumber": null,
            "bookingPrice": 0,
            "orgId": 434,
            "quoteId": 6557,
            "createdAt": "2024-04-18T00:00:00",
            "updatedAt": "2024-04-23T00:00:00",
            "createdBy": 444,
            "updatedBy": 442,
            "shipmentDate": "2024-04-18T00:00:00",
            "vesselImo": 0,
            "quoteNumber": null,
            "container": "[{\"container_id\":61521,\"container_type\":\"40 Standard Dry\",\"quantity\":2}]",
            "internalStatus": "booking-lineconfirmed",
            "loadType": "Ocean FCL",
            "taxInfo": "{\"title\":\"COST SENSITIVE\",\"id\":322,\"isShow\":true,\"price\":13838559.838145467,\"transit_time\":\"22\",\"Carrier\":\"AA FREIGHT INC.\",\"cutoffdate\":\"2024-04-18T08:07:52.649Z\",\"sailingdate\":\"2024-04-18T08:07:51.851Z\",\"handoverDate\":\"2024-04-24T18:30:00\+00:00\",\"icd\":null,\"pol\":{\"locationId\":1114,\"locationName\":\"Mundra\",\"isActive\":true,\"locationCode\":\"INMUN\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"pod\":{\"locationId\":1241,\"locationName\":\"Jebel Ali\",\"isActive\":true,\"locationCode\":\"AEJEA\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"originDetentionDays\":null,\"originDemurrageDays\":null,\"destinationDetentionDays\":null,\"destinationDemurrageDays\":null,\"gst\":2110966.754971342,\"payTerm\":null,\"quoteSensitivity\":\"Cost sensitive\"}",
            "isSailOnBooking": true,
            "isPayLater": false,
            "daysLater": 0,
            "vesselName": "sdad33",
            "sailingDate": null,
            "issues": [],
            "bookingETD": null,
            "containerList": [],
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "bookingPaymentTerms": null,
            "por": null,
            "pdaAccount": null,
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": "{}",
            "palletDetails": "{}"
        },
        {
            "source": {
                "locationId": 1114,
                "city": "Mundra",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUN"
            },
            "destination": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "insurance": false,
            "containers": [],
            "bookingIssue": 0,
            "customerName": "Australia1",
            "dateNote": null,
            "loyatyPoints": 0,
            "bookingPercent": 0,
            "bookingId": 944,
            "bookingName": "B240400944",
            "bookingDate": "2024-04-16T00:00:00",
            "bookingType": null,
            "fromLocation": 1114,
            "toLocation": 1241,
            "pickAddress": 606,
            "dropAddress": 603,
            "cargoHazRemarks": null,
            "cargoRefer": "",
            "carbonKWG": "0",
            "carbonEmission": "0",
            "quoteRemarks": "",
            "bookingService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":true,\"road\":{\"origin\":true,\"destination\":true},\"rail\":{\"origin\":true,\"destination\":true}},\"custom\":{\"origin\":true,\"destination\":true},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":true,\"at_factory\":false},\"destuffling\":{\"at_cfs\":false,\"at_factory\":true}},\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":{},\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "cargoReadyDate": "2024-04-17T00:00:00+00:00",
            "bookingTerms": null,
            "tripId": "",
            "vesselId": "32135",
            "voyoageId": null,
            "cargoHaz": false,
            "incoterm": "CIF",
            "carbonFootprint": true,
            "tradeFinance": true,
            "bookingAmount": 265215.49088845344,
            "bookingStatus": "booking-awaitingpayment",
            "bookingTags": "{}",
            "bookingAssignedTo": null,
            "salesPerson": null,
            "bookingUser": null,
            "additionalService": "{\"isaddition_service\":true,\"addition_service\":[],\"cargo_insurance\":null,\"iscarbon_offset\":false,\"carbon_offset\":null,\"special_request\":\"\"}",
            "bookingCurrency": null,
            "bookingETA": null,
            "bookingNumber": null,
            "bookingPrice": 0,
            "orgId": 434,
            "quoteId": 6550,
            "createdAt": "2024-04-16T00:00:00",
            "updatedAt": "2024-04-23T00:00:00",
            "createdBy": 444,
            "updatedBy": 442,
            "shipmentDate": "2024-04-16T00:00:00",
            "vesselImo": 0,
            "quoteNumber": null,
            "container": "[{\"container_id\":61521,\"container_type\":\"40 Standard Dry\",\"quantity\":2}]",
            "internalStatus": "booking-payment",
            "loadType": "Ocean FCL",
            "taxInfo": "{\"id\":321,\"title\":\"PREFERRED PARTNER\",\"isShow\":true,\"price\":265215.49088845344,\"transit_time\":\"22\",\"Carrier\":\"AA FREIGHT INC.\",\"icd\":null,\"pol\":{\"locationId\":1114,\"locationName\":\"Mundra\",\"isActive\":true,\"locationCode\":\"INMUN\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"pod\":{\"locationId\":1241,\"locationName\":\"Jebel Ali\",\"isActive\":true,\"locationCode\":\"AEJEA\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"cutoffdate\":\"2024-04-16T12:47:49.984Z\",\"sailingdate\":\"2024-04-16T12:47:48.915Z\",\"handoverDate\":\"2024-04-17T00:00:00\+00:00\",\"originDetentionDays\":\"3\",\"originDemurrageDays\":\"4\",\"destinationDetentionDays\":\"5\",\"destinationDemurrageDays\":\"5\",\"gst\":40456.60030501831,\"payTerm\":null,\"quoteSensitivity\":\"Cost sensitive\"}",
            "isSailOnBooking": true,
            "isPayLater": false,
            "daysLater": 0,
            "vesselName": "32135",
            "sailingDate": null,
            "issues": [],
            "bookingETD": null,
            "containerList": [],
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "bookingPaymentTerms": null,
            "por": null,
            "pdaAccount": null,
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": null,
            "palletDetails": null
        },
        {
            "source": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "destination": {
                "locationId": 1246,
                "city": "Mumbai",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUM"
            },
            "insurance": false,
            "containers": [],
            "bookingIssue": 0,
            "customerName": "Australia1",
            "dateNote": null,
            "loyatyPoints": 0,
            "bookingPercent": 0,
            "bookingId": 940,
            "bookingName": "B240400940",
            "bookingDate": "2024-04-15T00:00:00",
            "bookingType": null,
            "fromLocation": 1241,
            "toLocation": 1246,
            "pickAddress": 0,
            "dropAddress": 0,
            "cargoHazRemarks": null,
            "cargoRefer": "",
            "carbonKWG": null,
            "carbonEmission": null,
            "quoteRemarks": "",
            "bookingService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":false,\"road\":{\"origin\":false,\"destination\":false},\"rail\":{\"origin\":false,\"destination\":false}},\"custom\":{\"origin\":false,\"destination\":false},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":false,\"at_factory\":false},\"destuffling\":{\"at_cfs\":false,\"at_factory\":false}},\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":{},\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "cargoReadyDate": "2024-04-18T11:00:00+00:00",
            "bookingTerms": null,
            "tripId": "",
            "vesselId": "dasdaw",
            "voyoageId": null,
            "cargoHaz": false,
            "incoterm": "DAP",
            "carbonFootprint": true,
            "tradeFinance": true,
            "bookingAmount": 26778371.267397292,
            "bookingStatus": "booking-awaitingpayment",
            "bookingTags": "{}",
            "bookingAssignedTo": null,
            "salesPerson": null,
            "bookingUser": null,
            "additionalService": "{\"isaddition_service\":false,\"addition_service\":[],\"iscargo_insurance\":false,\"cargo_insurance\":null,\"iscarbon_offset\":false,\"carbon_offset\":null,\"special_request\":\"\"}",
            "bookingCurrency": null,
            "bookingETA": null,
            "bookingNumber": null,
            "bookingPrice": 0,
            "orgId": 434,
            "quoteId": 6535,
            "createdAt": "2024-04-15T00:00:00",
            "updatedAt": "2024-04-23T00:00:00",
            "createdBy": 444,
            "updatedBy": 442,
            "shipmentDate": "2024-04-15T00:00:00",
            "vesselImo": 0,
            "quoteNumber": null,
            "container": "[{\"container_id\":61521,\"container_type\":\"40 Standard Dry\",\"quantity\":3}]",
            "internalStatus": "booking-payment",
            "loadType": "Ocean FCL",
            "taxInfo": "{\"id\":321,\"title\":\"PREFERRED PARTNER\",\"isShow\":true,\"price\":26778371.267397292,\"transit_time\":\"33\",\"Carrier\":\"American President Lines (APL)\",\"icd\":null,\"pol\":{\"locationId\":1241,\"locationName\":\"Jebel Ali\",\"isActive\":true,\"locationCode\":\"AEJEA\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"pod\":{\"locationId\":2085,\"locationName\":\"Porticello\",\"isActive\":true,\"locationCode\":\"ITORL\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"cutoffdate\":\"2024-04-15T09:41:00.041Z\",\"sailingdate\":\"2024-04-15T09:40:59.438Z\",\"handoverDate\":\"2024-04-17T18:30:00\+00:00\",\"originDetentionDays\":\"3\",\"originDemurrageDays\":\"2\",\"destinationDetentionDays\":\"3\",\"destinationDemurrageDays\":\"4\",\"gst\":4084836.2950267065,\"payTerm\":null,\"quoteSensitivity\":\"Time sensitive\"}",
            "isSailOnBooking": true,
            "isPayLater": false,
            "daysLater": 0,
            "vesselName": "dasdaw",
            "sailingDate": null,
            "issues": [],
            "bookingETD": null,
            "containerList": [],
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "bookingPaymentTerms": null,
            "por": null,
            "pdaAccount": null,
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": null,
            "palletDetails": null
        },
        {
            "source": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "destination": {
                "locationId": 1246,
                "city": "Mumbai",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUM"
            },
            "insurance": false,
            "containers": [
                {
                    "containerId": 265,
                    "portId": 0,
                    "containerNumber": "TRLU9320234",
                    "containerBl": "dsd",
                    "bookingNumber": "B240400939",
                    "containerSize": "",
                    "doNumber": "fdsa",
                    "doDate": "2024-04-15T09:28:25.236Z",
                    "doCopy": "",
                    "vesselNumber": "",
                    "voyageNumber": "",
                    "evgm": "",
                    "gateInETA": null,
                    "gateInATA": null,
                    "moveRequest": null,
                    "moveDate": null,
                    "mfgDate": null,
                    "remarks": "",
                    "packingList": null,
                    "shimpmentType": "",
                    "containterType": "{\"id\":117,\"name\":\"20 Standard Dry\"}",
                    "maxPayload": null,
                    "grossWeight": null,
                    "toPort": "{\"locationId\":1246,\"city\":\"Mumbai\",\"country\":{\"id\":\"IN\",\"name\":\"India\"},\"port\":\"INMUM\"}",
                    "fromPort": "{\"locationId\":1241,\"city\":\"Jebel Ali\",\"country\":{\"id\":\"AE\",\"name\":\"UAE\"},\"port\":\"AEJEA\"}",
                    "containerOperator": null,
                    "containerCargo": "{\"id\":79,\"name\":\"General\"}",
                    "bookingId": 939,
                    "igmNumber": "",
                    "eSeal": "",
                    "booking": null,
                    "vesselName": null,
                    "rollOver": null,
                    "sailingDate": null,
                    "vehicles": null
                }
            ],
            "bookingIssue": 0,
            "customerName": "Australia1",
            "dateNote": null,
            "loyatyPoints": 0,
            "bookingPercent": 0,
            "bookingId": 939,
            "bookingName": "B240400939",
            "bookingDate": "2024-04-15T00:00:00",
            "bookingType": null,
            "fromLocation": 1241,
            "toLocation": 1246,
            "pickAddress": 0,
            "dropAddress": 0,
            "cargoHazRemarks": null,
            "cargoRefer": "",
            "carbonKWG": null,
            "carbonEmission": null,
            "quoteRemarks": "",
            "bookingService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":false,\"road\":{\"origin\":false,\"destination\":false},\"rail\":{\"origin\":false,\"destination\":false}},\"custom\":{\"origin\":false,\"destination\":false},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":false,\"at_factory\":false},\"destuffling\":{\"at_cfs\":false,\"at_factory\":false}},\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":{},\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "cargoReadyDate": "2024-04-17T18:30:00+00:00",
            "bookingTerms": null,
            "tripId": "",
            "vesselId": "dsad222",
            "voyoageId": null,
            "cargoHaz": false,
            "incoterm": "DAP",
            "carbonFootprint": true,
            "tradeFinance": true,
            "bookingAmount": 6924668.222475656,
            "bookingStatus": "booking-awaitingcontainerallocation",
            "bookingTags": "{\"active\":\"default\"}",
            "bookingAssignedTo": null,
            "salesPerson": null,
            "bookingUser": null,
            "additionalService": "{\"isaddition_service\":false,\"addition_service\":null,\"iscargo_insurance\":false,\"cargo_insurance\":null,\"iscarbon_offset\":false,\"carbon_offset\":null,\"special_request\":\"\"}",
            "bookingCurrency": null,
            "bookingETA": null,
            "bookingNumber": null,
            "bookingPrice": 0,
            "orgId": 434,
            "quoteId": 6533,
            "createdAt": "2024-04-15T00:00:00",
            "updatedAt": "2024-04-15T00:00:00",
            "createdBy": 444,
            "updatedBy": 442,
            "shipmentDate": "2024-04-15T00:00:00",
            "vesselImo": 0,
            "quoteNumber": null,
            "container": "[{\"container_id\":61521,\"container_type\":\"40 Standard Dry\",\"quantity\":3,\"doNumber\":\"fdsa\"}]",
            "internalStatus": "booking-operations",
            "loadType": "Ocean FCL",
            "taxInfo": "{\"id\":321,\"title\":\"PREFERRED PARTNER\",\"isShow\":true,\"price\":6924668.222475656,\"transit_time\":\"222\",\"Carrier\":\"American President Lines (APL)\",\"icd\":null,\"pol\":{\"locationId\":1241,\"locationName\":\"Jebel Ali\",\"isActive\":true,\"locationCode\":\"AEJEA\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"pod\":{\"locationId\":2085,\"locationName\":\"Porticello\",\"isActive\":true,\"locationCode\":\"ITORL\",\"locationCountry\":\"\",\"locationGeo\":\"\",\"locationAddress\":\"\",\"locationPhone\":\"\",\"locationFax\":null,\"locationEmail\":null,\"locationType\":\"PORT\",\"nearestCFS\":\"\",\"nearestPort\":\"\",\"shipmentLocationId\":null},\"cutoffdate\":\"2024-04-15T06:39:34.383Z\",\"sailingdate\":\"2024-04-15T06:39:33.475Z\",\"handoverDate\":\"2024-04-17T18:30:00\+00:00\",\"originDetentionDays\":22,\"originDemurrageDays\":null,\"destinationDetentionDays\":null,\"destinationDemurrageDays\":null,\"gst\":1234299.676045618,\"payTerm\":null,\"quoteSensitivity\":\"Time sensitive\"}",
            "isSailOnBooking": true,
            "isPayLater": false,
            "daysLater": 0,
            "vesselName": "dsad222",
            "sailingDate": null,
            "issues": [],
            "bookingETD": null,
            "containerList": [
                "TRLU9320234"
            ],
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "bookingPaymentTerms": null,
            "por": null,
            "pdaAccount": null,
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": null,
            "palletDetails": null
        }
    ],
    items2: [
        {
            "bookingInvoices": [
                {
                    "source": null,
                    "destination": null,
                    "invoiceId": 983,
                    "invoiceDate": "2024-04-19T00:00:00",
                    "orgId": 434,
                    "orgName": "Australia1",
                    "bookingId": 947,
                    "bookingName": "B240400947",
                    "bookingDate": "2024-04-18T00:00:00",
                    "bookingType": 96,
                    "fromLocation": 1114,
                    "toLocation": 1241,
                    "dueDate": "0001-01-01T00:00:00",
                    "remarks": null,
                    "invoiceAmount": 123751.93237778197,
                    "discount": 0,
                    "coupon": null,
                    "invoiceType": "{\"id\":375,\"name\":\"Proforma Invoice\"}",
                    "payment": null,
                    "invoiceStatus": "invoice-paid",
                    "invoiceItems": [],
                    "createdAt": "2024-04-19T00:00:00",
                    "updatedAt": "2024-04-19T00:00:00",
                    "createdBy": 0,
                    "updatedBy": 442,
                    "paymentOrderId": null,
                    "paymentReceipt": null,
                    "invoiceDocuments": "{\"documentId\":4100,\"filename\":\"blob\"}",
                    "invoiceNumber": "I240400983",
                    "internalStatus": null
                }
            ],
            "source": {
                "locationId": 1114,
                "city": "Mundra",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUN"
            },
            "destination": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "insurance": false,
            "containers": [],
            "bookingIssue": 0,
            "customerName": "Australia1",
            "dateNote": null,
            "loyatyPoints": 0,
            "bookingPercent": 0,
            "bookingId": 947,
            "bookingName": "B240400947",
            "bookingDate": "2024-04-18T00:00:00",
            "bookingType": null,
            "fromLocation": 1114,
            "toLocation": 1241,
            "pickAddress": 0,
            "dropAddress": 0,
            "cargoHazRemarks": null,
            "cargoRefer": "",
            "carbonKWG": "0",
            "carbonEmission": "0",
            "quoteRemarks": "",
            "bookingService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":false,\"road\":{\"origin\":false,\"destination\":false},\"rail\":{\"origin\":false,\"destination\":false}},\"custom\":{\"origin\":false,\"destination\":false},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":false,\"at_factory\":false},\"destuffling\":{\"at_cfs\":false,\"at_factory\":false}},\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":null,\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "cargoReadyDate": "2024-04-23T18:30:00+00:00",
            "bookingTerms": null,
            "tripId": "",
            "vesselId": null,
            "voyoageId": null,
            "cargoHaz": false,
            "incoterm": "CIF",
            "carbonFootprint": true,
            "tradeFinance": true,
            "bookingAmount": 123751.93237778197,
            "bookingStatus": "booking-completed",
            "bookingTags": "{}",
            "bookingAssignedTo": null,
            "salesPerson": null,
            "bookingUser": null,
            "additionalService": "{\"isaddition_service\":false,\"addition_service\":[],\"cargo_insurance\":null,\"iscarbon_offset\":false,\"carbon_offset\":null,\"special_request\":\"\"}",
            "bookingCurrency": null,
            "bookingETA": null,
            "bookingNumber": null,
            "bookingPrice": 0,
            "orgId": 434,
            "quoteId": 6556,
            "createdAt": "2024-04-18T00:00:00",
            "updatedAt": "2024-04-23T00:00:00",
            "createdBy": 444,
            "updatedBy": 442,
            "shipmentDate": "2024-04-18T00:00:00",
            "vesselImo": 0,
            "quoteNumber": null,
            "container": "[{\"container_id\":0,\"container_type\":\"\",\"quantity\":0}]",
            "internalStatus": "booking-completed",
            "loadType": "Ocean LCL",
            "taxInfo": null,
            "isSailOnBooking": true,
            "isPayLater": false,
            "daysLater": 0,
            "vesselName": null,
            "sailingDate": null,
            "issues": [],
            "bookingETD": null,
            "containerList": [],
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "bookingPaymentTerms": null,
            "por": null,
            "pdaAccount": null,
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": "{}",
            "palletDetails": "[{\"palletType\":\"1219 mm x 1016 mm\",\"quantity\":12}]"
        },
        {
            "bookingInvoices": [
                {
                    "source": null,
                    "destination": null,
                    "invoiceId": 984,
                    "invoiceDate": "2024-04-19T00:00:00",
                    "orgId": 434,
                    "orgName": "Australia1",
                    "bookingId": 944,
                    "bookingName": "B240400944",
                    "bookingDate": "2024-04-16T00:00:00",
                    "bookingType": 96,
                    "fromLocation": 1114,
                    "toLocation": 1241,
                    "dueDate": "0001-01-01T00:00:00",
                    "remarks": null,
                    "invoiceAmount": 265215.49088845344,
                    "discount": 0,
                    "coupon": null,
                    "invoiceType": "{\"id\":375,\"name\":\"Proforma Invoice\"}",
                    "payment": null,
                    "invoiceStatus": "invoice-generated",
                    "invoiceItems": [],
                    "createdAt": "2024-04-19T00:00:00",
                    "updatedAt": "2024-04-19T00:00:00",
                    "createdBy": 0,
                    "updatedBy": 442,
                    "paymentOrderId": null,
                    "paymentReceipt": null,
                    "invoiceDocuments": "{\"documentId\":4103,\"filename\":\"blob\"}",
                    "invoiceNumber": "I240400984",
                    "internalStatus": null
                }
            ],
            "source": {
                "locationId": 1114,
                "city": "Mundra",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUN"
            },
            "destination": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "insurance": false,
            "containers": [],
            "bookingIssue": 0,
            "customerName": "Australia1",
            "dateNote": null,
            "loyatyPoints": 0,
            "bookingPercent": 0,
            "bookingId": 944,
            "bookingName": "B240400944",
            "bookingDate": "2024-04-16T00:00:00",
            "bookingType": null,
            "fromLocation": 1114,
            "toLocation": 1241,
            "pickAddress": 606,
            "dropAddress": 603,
            "cargoHazRemarks": null,
            "cargoRefer": "",
            "carbonKWG": "0",
            "carbonEmission": "0",
            "quoteRemarks": "",
            "bookingService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":true,\"road\":{\"origin\":true,\"destination\":true},\"rail\":{\"origin\":true,\"destination\":true}},\"custom\":{\"origin\":true,\"destination\":true},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":true,\"at_factory\":false},\"destuffling\":{\"at_cfs\":false,\"at_factory\":true}},\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":{},\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "cargoReadyDate": "2024-04-17T00:00:00+00:00",
            "bookingTerms": null,
            "tripId": "",
            "vesselId": "32135",
            "voyoageId": null,
            "cargoHaz": false,
            "incoterm": "CIF",
            "carbonFootprint": true,
            "tradeFinance": true,
            "bookingAmount": 265215.49088845344,
            "bookingStatus": "booking-awaitingpayment",
            "bookingTags": "{}",
            "bookingAssignedTo": null,
            "salesPerson": null,
            "bookingUser": null,
            "additionalService": "{\"isaddition_service\":true,\"addition_service\":[],\"cargo_insurance\":null,\"iscarbon_offset\":false,\"carbon_offset\":null,\"special_request\":\"\"}",
            "bookingCurrency": null,
            "bookingETA": null,
            "bookingNumber": null,
            "bookingPrice": 0,
            "orgId": 434,
            "quoteId": 6550,
            "createdAt": "2024-04-16T00:00:00",
            "updatedAt": "2024-04-23T00:00:00",
            "createdBy": 444,
            "updatedBy": 442,
            "shipmentDate": "2024-04-16T00:00:00",
            "vesselImo": 0,
            "quoteNumber": null,
            "container": "[{\"container_id\":61521,\"container_type\":\"40 Standard Dry\",\"quantity\":2}]",
            "internalStatus": "booking-payment",
            "loadType": "Ocean FCL",
            "taxInfo": null,
            "isSailOnBooking": true,
            "isPayLater": false,
            "daysLater": 0,
            "vesselName": "32135",
            "sailingDate": null,
            "issues": [],
            "bookingETD": null,
            "containerList": [],
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "bookingPaymentTerms": null,
            "por": null,
            "pdaAccount": null,
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": null,
            "palletDetails": null
        },
        {
            "bookingInvoices": [
                {
                    "source": null,
                    "destination": null,
                    "invoiceId": 980,
                    "invoiceDate": "2024-04-15T00:00:00",
                    "orgId": 434,
                    "orgName": "Australia1",
                    "bookingId": 940,
                    "bookingName": "B240400940",
                    "bookingDate": "2024-04-15T00:00:00",
                    "bookingType": 96,
                    "fromLocation": 1241,
                    "toLocation": 1246,
                    "dueDate": "0001-01-01T00:00:00",
                    "remarks": null,
                    "invoiceAmount": 26778371.267397292,
                    "discount": 0,
                    "coupon": null,
                    "invoiceType": "{\"id\":375,\"name\":\"Proforma Invoice\"}",
                    "payment": null,
                    "invoiceStatus": "invoice-generated",
                    "invoiceItems": [],
                    "createdAt": "2024-04-15T00:00:00",
                    "updatedAt": "2024-04-15T00:00:00",
                    "createdBy": 0,
                    "updatedBy": 442,
                    "paymentOrderId": null,
                    "paymentReceipt": null,
                    "invoiceDocuments": "{\"documentId\":4076,\"filename\":\"blob\"}",
                    "invoiceNumber": "I240400980",
                    "internalStatus": null
                }
            ],
            "source": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "destination": {
                "locationId": 1246,
                "city": "Mumbai",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUM"
            },
            "insurance": false,
            "containers": [],
            "bookingIssue": 0,
            "customerName": "Australia1",
            "dateNote": null,
            "loyatyPoints": 0,
            "bookingPercent": 0,
            "bookingId": 940,
            "bookingName": "B240400940",
            "bookingDate": "2024-04-15T00:00:00",
            "bookingType": null,
            "fromLocation": 1241,
            "toLocation": 1246,
            "pickAddress": 0,
            "dropAddress": 0,
            "cargoHazRemarks": null,
            "cargoRefer": "",
            "carbonKWG": null,
            "carbonEmission": null,
            "quoteRemarks": "",
            "bookingService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":false,\"road\":{\"origin\":false,\"destination\":false},\"rail\":{\"origin\":false,\"destination\":false}},\"custom\":{\"origin\":false,\"destination\":false},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":false,\"at_factory\":false},\"destuffling\":{\"at_cfs\":false,\"at_factory\":false}},\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":{},\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "cargoReadyDate": "2024-04-18T11:00:00+00:00",
            "bookingTerms": null,
            "tripId": "",
            "vesselId": "dasdaw",
            "voyoageId": null,
            "cargoHaz": false,
            "incoterm": "DAP",
            "carbonFootprint": true,
            "tradeFinance": true,
            "bookingAmount": 26778371.267397292,
            "bookingStatus": "booking-awaitingpayment",
            "bookingTags": "{}",
            "bookingAssignedTo": null,
            "salesPerson": null,
            "bookingUser": null,
            "additionalService": "{\"isaddition_service\":false,\"addition_service\":[],\"iscargo_insurance\":false,\"cargo_insurance\":null,\"iscarbon_offset\":false,\"carbon_offset\":null,\"special_request\":\"\"}",
            "bookingCurrency": null,
            "bookingETA": null,
            "bookingNumber": null,
            "bookingPrice": 0,
            "orgId": 434,
            "quoteId": 6535,
            "createdAt": "2024-04-15T00:00:00",
            "updatedAt": "2024-04-23T00:00:00",
            "createdBy": 444,
            "updatedBy": 442,
            "shipmentDate": "2024-04-15T00:00:00",
            "vesselImo": 0,
            "quoteNumber": null,
            "container": "[{\"container_id\":61521,\"container_type\":\"40 Standard Dry\",\"quantity\":3}]",
            "internalStatus": "booking-payment",
            "loadType": "Ocean FCL",
            "taxInfo": null,
            "isSailOnBooking": true,
            "isPayLater": false,
            "daysLater": 0,
            "vesselName": "dasdaw",
            "sailingDate": null,
            "issues": [],
            "bookingETD": null,
            "containerList": [],
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "bookingPaymentTerms": null,
            "por": null,
            "pdaAccount": null,
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": null,
            "palletDetails": null
        },
        {
            "bookingInvoices": [
                {
                    "source": null,
                    "destination": null,
                    "invoiceId": 971,
                    "invoiceDate": "2024-04-15T00:00:00",
                    "orgId": 434,
                    "orgName": "Australia1",
                    "bookingId": 939,
                    "bookingName": "B240400939",
                    "bookingDate": "2024-04-15T00:00:00",
                    "bookingType": 96,
                    "fromLocation": 1241,
                    "toLocation": 1246,
                    "dueDate": "2024-04-16T00:00:00",
                    "remarks": null,
                    "invoiceAmount": 2121,
                    "discount": 0,
                    "coupon": null,
                    "invoiceType": "{\"id\":377,\"name\":\"Additional Invoice\"}",
                    "payment": null,
                    "invoiceStatus": "invoice-paid",
                    "invoiceItems": [],
                    "createdAt": "2024-04-15T00:00:00",
                    "updatedAt": "2024-04-15T00:00:00",
                    "createdBy": 442,
                    "updatedBy": 442,
                    "paymentOrderId": null,
                    "paymentReceipt": null,
                    "invoiceDocuments": "{\"documentId\":4047,\"filename\":\"priceOption (2)\"}",
                    "invoiceNumber": "I240400971",
                    "internalStatus": null
                },
                {
                    "source": null,
                    "destination": null,
                    "invoiceId": 972,
                    "invoiceDate": "2024-04-15T00:00:00",
                    "orgId": 434,
                    "orgName": "Australia1",
                    "bookingId": 939,
                    "bookingName": "B240400939",
                    "bookingDate": "2024-04-15T00:00:00",
                    "bookingType": 96,
                    "fromLocation": 1241,
                    "toLocation": 1246,
                    "dueDate": "0001-01-01T00:00:00",
                    "remarks": null,
                    "invoiceAmount": 6924668.222475656,
                    "discount": 0,
                    "coupon": null,
                    "invoiceType": "{\"id\":375,\"name\":\"Proforma Invoice\"}",
                    "payment": null,
                    "invoiceStatus": "invoice-paid",
                    "invoiceItems": [],
                    "createdAt": "2024-04-15T00:00:00",
                    "updatedAt": "2024-04-15T00:00:00",
                    "createdBy": 0,
                    "updatedBy": 442,
                    "paymentOrderId": null,
                    "paymentReceipt": null,
                    "invoiceDocuments": "{\"documentId\":4048,\"filename\":\"blob\"}",
                    "invoiceNumber": "I240400972",
                    "internalStatus": null
                }
            ],
            "source": {
                "locationId": 1241,
                "city": "Jebel Ali",
                "country": "{\"id\":\"AE\",\"name\":\"UAE\"}",
                "port": "AEJEA"
            },
            "destination": {
                "locationId": 1246,
                "city": "Mumbai",
                "country": "{\"id\":\"IN\",\"name\":\"India\"}",
                "port": "INMUM"
            },
            "insurance": false,
            "containers": [
                {
                    "containerId": 265,
                    "portId": 0,
                    "containerNumber": "TRLU9320234",
                    "containerBl": "dsd",
                    "bookingNumber": "B240400939",
                    "containerSize": "",
                    "doNumber": "fdsa",
                    "doDate": "2024-04-15T09:28:25.236Z",
                    "doCopy": "",
                    "vesselNumber": "",
                    "voyageNumber": "",
                    "evgm": "",
                    "gateInETA": null,
                    "gateInATA": null,
                    "moveRequest": null,
                    "moveDate": null,
                    "mfgDate": null,
                    "remarks": "",
                    "packingList": null,
                    "shimpmentType": "",
                    "containterType": "{\"id\":117,\"name\":\"20 Standard Dry\"}",
                    "maxPayload": null,
                    "grossWeight": null,
                    "toPort": "{\"locationId\":1246,\"city\":\"Mumbai\",\"country\":{\"id\":\"IN\",\"name\":\"India\"},\"port\":\"INMUM\"}",
                    "fromPort": "{\"locationId\":1241,\"city\":\"Jebel Ali\",\"country\":{\"id\":\"AE\",\"name\":\"UAE\"},\"port\":\"AEJEA\"}",
                    "containerOperator": null,
                    "containerCargo": "{\"id\":79,\"name\":\"General\"}",
                    "bookingId": 939,
                    "igmNumber": "",
                    "eSeal": "",
                    "booking": null,
                    "vesselName": null,
                    "rollOver": null,
                    "sailingDate": null,
                    "vehicles": null
                }
            ],
            "bookingIssue": 0,
            "customerName": "Australia1",
            "dateNote": null,
            "loyatyPoints": 0,
            "bookingPercent": 0,
            "bookingId": 939,
            "bookingName": "B240400939",
            "bookingDate": "2024-04-15T00:00:00",
            "bookingType": null,
            "fromLocation": 1241,
            "toLocation": 1246,
            "pickAddress": 0,
            "dropAddress": 0,
            "cargoHazRemarks": null,
            "cargoRefer": "",
            "carbonKWG": null,
            "carbonEmission": null,
            "quoteRemarks": "",
            "bookingService": "{\"ocean\":{\"type\":\"Export\"},\"land\":{\"isLand\":false,\"road\":{\"origin\":false,\"destination\":false},\"rail\":{\"origin\":false,\"destination\":false}},\"custom\":{\"origin\":false,\"destination\":false},\"cfs_icd\":{\"stuffling\":{\"at_cfs\":false,\"at_factory\":false},\"destuffling\":{\"at_cfs\":false,\"at_factory\":false}},\"isWarehousing\":false,\"isCarbonOffset\":false,\"isFumigation\":false,\"carbondetail\":{},\"special_request\":\"\",\"carbonoffset\":{\"carbonKWG\":\"\",\"carbonEmission\":\"\",\"carbonFootprint\":true}}",
            "cargoReadyDate": "2024-04-17T18:30:00+00:00",
            "bookingTerms": null,
            "tripId": "",
            "vesselId": "dsad222",
            "voyoageId": null,
            "cargoHaz": false,
            "incoterm": "DAP",
            "carbonFootprint": true,
            "tradeFinance": true,
            "bookingAmount": 6924668.222475656,
            "bookingStatus": "booking-awaitingcontainerallocation",
            "bookingTags": "{\"active\":\"default\"}",
            "bookingAssignedTo": null,
            "salesPerson": null,
            "bookingUser": null,
            "additionalService": "{\"isaddition_service\":false,\"addition_service\":null,\"iscargo_insurance\":false,\"cargo_insurance\":null,\"iscarbon_offset\":false,\"carbon_offset\":null,\"special_request\":\"\"}",
            "bookingCurrency": null,
            "bookingETA": null,
            "bookingNumber": null,
            "bookingPrice": 0,
            "orgId": 434,
            "quoteId": 6533,
            "createdAt": "2024-04-15T00:00:00",
            "updatedAt": "2024-04-15T00:00:00",
            "createdBy": 444,
            "updatedBy": 442,
            "shipmentDate": "2024-04-15T00:00:00",
            "vesselImo": 0,
            "quoteNumber": null,
            "container": "[{\"container_id\":61521,\"container_type\":\"40 Standard Dry\",\"quantity\":3,\"doNumber\":\"fdsa\"}]",
            "internalStatus": "booking-operations",
            "loadType": "Ocean FCL",
            "taxInfo": null,
            "isSailOnBooking": true,
            "isPayLater": false,
            "daysLater": 0,
            "vesselName": "dsad222",
            "sailingDate": null,
            "issues": [],
            "bookingETD": null,
            "containerList": [
                "TRLU9320234"
            ],
            "exchangeRate": null,
            "receivedDocument": null,
            "otherDocument": null,
            "fpod": null,
            "rateFilledBy": null,
            "stuffingLocation": null,
            "blType": null,
            "freeDayRequired": null,
            "bookingParty": null,
            "bookingOffice": null,
            "humidity": "",
            "cargoValues": "",
            "bookingPaymentTerms": null,
            "por": null,
            "pdaAccount": null,
            "destChargesTerm": null,
            "billingParty": "{}",
            "preferedAirLine": null,
            "palletDetails": null
        }
    ]
}